version: '2'
services:
  tablebuilder1:
    image: remythemsen/tablebuilder:1.0
    volumes:
     - ./tablebuilder/data:/opt/docker/data

  tablebuilder2:
    image: remythemsen/tablebuilder:1.0
    volumes:
     - ./tablebuilder/data:/opt/docker/data

  performance:
    image: remythemsen/performance:1.0
    links:
      - tablebuilder1:tablebuilder1
      - tablebuilder2:tablebuilder2
